### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by owlcloud** [AHGGG/poe-node-api#1]
Will you continue to develop? Is there or will there be an opportunity to save the context of the dialogue and start it not for me alone, but for other people? For example, I want to create a telegram bot through which my team will be able to communicate with the bot individually, that is, without being tied to a single chat.

**Comment by AHGGG** [comment]
The answer to the first question is yes. And my understanding of "save the context" is that you want to add some domain-sepecific context and link it to telegram bot, your team can open any chat based on the domain-specific knowledge? (similar to ChatGPT's fine-tuning?)

**Comment by AHGGG** [comment]
> Will you continue to develop? Is there or will there be an opportunity to save the context of the dialogue and start it not for me alone, but for other people? For example, I want to create a telegram bot through which my team will be able to communicate with the bot individually, that is, without being tied to a single chat.

The answer to the first question is yes. And my understanding of "save the context" is that you want to add some domain-sepecific context and link it to telegram bot, your team can open any chat based on the domain-specific knowledge? (similar to ChatGPT's fine-tuning?)

**Comment by owlcloud** [comment]
The question is precisely in creating chat sessions for several people.
Ability to transmit a unique conversionId

**Comment by AHGGG** [comment]
> The question is precisely in creating chat sessions for several people. Ability to transmit a unique conversionId

For now, I have no idea about this because the context is stored in the server, and the message is sent separately. Unlike ChatGPT, ChatGPT will carry the context in the request.

**Comment by owlcloud** [comment]
There is some kind of project, also on typescript, where the creation of an account on the server is implemented. In principle, if you manage to pull out this algorithm from there and implement it yourself, then you will end up with a project completely with reverse engineering.
Link to the project https://github.com/muharamdani/poe
It turns out that there will be a certain identifier, for example, user id, when it first appears, an account for poe will be created automatically for it, and then all conversions will be individual.
Can I ask you to implement this?)

**Comment by AHGGG** [comment]
> There is some kind of project, also on typescript, where the creation of an account on the server is implemented. In principle, if you manage to pull out this algorithm from there and implement it yourself, then you will end up with a project completely with reverse engineering. Link to the project https://github.com/muharamdani/poe

I saw this before, but create acount automatically is not working now. I'll take a look and see if I can make some changes to make it usable again. But this may violate some regulations and bring pressure to the official free services? I'm not sure if this can be done. This needs to be considered.

**Comment by owlcloud** [comment]
Temporary mail is free, poe also does not limit the number of messages to its bots, so why not?

**Comment by AHGGG** [comment]
> Temporary mail is free, poe also does not limit the number of messages to its bots, so why not?

I just tried it by using Free SMS service, looks like it's possible and I found a new graphql api. I will add this to TODO list, and develop this feature after ensuring the stability of existing functions.

**Comment by owlcloud** [comment]
And why not through the mail?

**Comment by AHGGG** [comment]
> And why not through the mail?

Login via SMS/email has already been added to the TODO list, and I will try implementing it after the client becomes more stable.

**Comment by owlcloud** [comment]
I understand, thank you, I don't have much time to work on this, but it would be a very useful library if it were implemented with such functionality. I believe in you :)
