### ISSUE TITLE
Error: Invalid token or no bots are available.

### ISSUE THREAD

**Issue by ghost** [AHGGG/poe-node-api#12]
Error:
```
Error: Invalid token or no bots are available. Might: network error, try to getDataNext first. Or Viewer dataStructure changed, please create an issue on github
```

My code:
api.js
```js
import { PoeClient } from "poe-node-api";

const client = new PoeClient({ logLevel: "debug" });

await client.init();

await client.sendMessage(content, "a2", true, (result) => {
  console.log(`${result}`);
});

callApiFunction("Hello this is Amey");
```

I ran by using `node api.js`

my package.json dependencies 
```json
  "dependencies": {
    "pino-pretty": "^10.0.0",
    "poe-node-api": "^0.0.6"
  }
```

**Comment by AHGGG** [comment]
The viewer data structure has changed again. The viewerBotList is missing. I will fix it.

**Comment by ghost** [comment]
thank you! if possible ping me here when you do so pls.

**Comment by AHGGG** [comment]
> thank you! if possible ping me here when you do so pls.

Try 0.0.7 @ameywtf

**Comment by ghost** [comment]
> > thank you! if possible ping me here when you do so pls.
> 
> Try 0.0.7 @ameywtf


I get this error 
```
[20:24:46.372] DEBUG: wsUrl:wss://tch709684.tch.quora.com/up/chan58-8888/updates?min_seq=26120880889&channel=poe-chan58-8888-pjtzadkwaehglvgvbqra&hash=2706803670475832097
[20:24:47.176] ERROR: Connection error
[20:24:47.176] ERROR: Socket connection timeout
```

**Comment by AHGGG** [comment]
It might be a network issue. Please try again. If you still encounter this problem, please let me know how to reproduce this bug.

**Comment by ghost** [comment]
Yes I think it was a network issue, It works now, thank you!
