### ISSUE TITLE
How to run this properly on Nodejs project?

### ISSUE THREAD

**Issue by DRAMA22** [AHGGG/poe-node-api#13]
Can you provide example for nodejs ? Since i couldn't succeed to compile it in nodejs i am not using typescript.

**Comment by AHGGG** [comment]
Try https://github.com/AHGGG/poe-node-api/issues/11#issuecomment-1569436321. And you must adapt to the latest version yourself.

**Comment by DRAMA22** [comment]
Well that's not the issue I faced. How ever it looks like its build to be used in typescript only.
