### ISSUE TITLE
getNextData获取后的数据没有携带availableBotsConnection，故此 if (!this.viewer['availableBotsConnection']) 抛出异常

### ISSUE THREAD

**Issue by HailHydra58** [AHGGG/poe-node-api#19]
init初始化的时候getNextData调用并返回的参数中的 viewer 参数里面缺少所需的availableBotsConnection。导致在getBots函数的第4行的if判断不过。应该是数据结构已经更改。麻烦哥们看看呢

**Comment by AHGGG** [comment]
好，估计是又变了

**Comment by AHGGG** [comment]
我这里看是好的，你检查下你的网络呢？

**Comment by HailHydra58** [comment]
> 我这里看是好的，你检查下你的网络呢？

是的，当我在poe网站上重新退出登录 在调用getNextData返回的数据就携带了 availableBotsConnection 了。在此之前我的梯子确认是没有问题的。看来碰到接口不返回 availableBotsConnection  可以重新登录一下

**Comment by AHGGG** [comment]
嗯，我一直用的是一个没过期的cookie做的测试，都没登录过网页端，快一个多月没变了都是好的。频繁的在网页上操作可能遇到未知问题，例如有时候加载不出来，最有可能就是网络问题。
