### ISSUE TITLE
fetch failed: https://poe.com/_next/data/t55y8LR_LPR9oghrT_Zdj/undefined.json, 404, Not Found

### ISSUE THREAD

**Issue by nxkiss** [AHGGG/poe-node-api#5]
Error: Failed to fetch https://poe.com/_next/data/t55y8LR_LPR9oghrT_Zdj/undefined.json after 5 retries
    at file:///C:/Users/rowan/Documents/bypassed/node_modules/poe-node-api/dist/PoeClient.js:93:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0

**Comment by AHGGG** [comment]
Did you add a custom bot?
Maybe I know why. I'll fix it.

**Comment by AHGGG** [comment]
> Error: Failed to fetch https://poe.com/_next/data/t55y8LR_LPR9oghrT_Zdj/undefined.json after 5 retries at file:///C:/Users/rowan/Documents/bypassed/node_modules/poe-node-api/dist/PoeClient.js:93:24 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.15.0

Try dev branch, I changed the logic of getBot :). And support sendMsg to custom bot.
Clone this repo. Checkout to dev branch. And refer to the example/example.ts file. Follow the temporary usage instructions.
