### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mrloldev** [AHGGG/poe-node-api#8]
Error: ```
fetch: https://poe.com, options: {
  method: 'GET',
  headers: { cookie: 'p-b=5Zcy9-%3D%3D' }
}
fetch: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/Sage.json, options: {
  method: 'GET',
  headers: { cookie: 'p-b=5Zcy9-%3D%3D' }
}
fetch: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/GPT-4.json, options: {
  method: 'GET',
  headers: { cookie: 'p-b=5Zcy9-%3D%3D' }
}
fetch: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/Claude+.json, options: {
  method: 'GET',
  headers: { cookie: 'p-b=5Zcy9-' }
}
fetch: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, options: {
  method: 'GET',
  headers: { cookie: 'p-b=5Zcy9-%%3D' }
}
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
retrying https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 1/5...22
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
retrying https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 2/5...25
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
retrying https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 3/5...27
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
retrying https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 4/5...30
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
retrying https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 5/5...32
        fetch failed: https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json, 404, Not Found
Error: Failed to fetch https://poe.com/_next/data/vV4vHhyH3i9fz-iA02t-2/undefined.json after 5 retries
    at file:///D:/projects/loick.team/projects/turing/dev/turing/turing-ai-api/node_modules/poe-node-api/dist/PoeClient.js:93:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by AHGGG** [comment]
try clone repo, use branch dev. Fixed but not update to npm. If you still meet undefined error, please let me know～

**Comment by mrloldev** [comment]
can you please update to npm?

**Comment by mrloldev** [comment]
is just 2mins and will reduce a lot my work

**Comment by AHGGG** [comment]
> is just 2mins and will reduce a lot my work

Ok, just give me five minutes. I just turned off the computer.

**Comment by mrloldev** [comment]
yes please

**Comment by AHGGG** [comment]
> yes please 

try 0.0.5
I'm going to sleep. If you still meet undefined error, please let me know～

**Comment by ghost** [comment]
this error still occurs for me


code:
```js
let client = new PoeClient({ debug: false });
await client.init();

await client.sendMessage(
  "write c++ code for finding the largest increasing subsequence",
  "a2",
  false,
  (result) => {
    console.log(result);
  }
);
```

**Comment by AHGGG** [comment]
> this error still occurs for me
> 
> code:
> 
> ```js
> let client = new PoeClient({ debug: false });
> await client.init();
> 
> await client.sendMessage(
>   "write c++ code for finding the largest increasing subsequence",
>   "a2",
>   false,
>   (result) => {
>     console.log(result);
>   }
> );
> ```

Try version 0.0.6.
